---
title: "STAT 580_HW4"
output: pdf_document
---
Q2

(a)
`
`
`
`
`
`
`
`
`
`
```{r}
x1 <- rexp(n = 1000000, rate = 1)
(int1 <- mean((x1^2+5)*x1))
```
(b)
`
`
`
`
`
`
`
`
`
`
```{r}
x2 <- rnorm(n = 1000000, sd = 1/sqrt(2))
(int2 <- mean(sin(x2)*sqrt(pi)/x2))
```
(c)
`
`
`
`
`
`
`
`
`
`
```{r}
x3 <- rexp(n = 1000000, rate = 1)
(int3 <- mean((4*x3)**(2/3)))
```

Q3
(1)
`
`
`
`
`
`
`
`
`
`
```{r}
v = 0.1
x1 <- rnorm(n = 1000000, mean = 1.5, sd = v)
vect <- ifelse(x1<2 & x1>1,v * exp(-x1^2/2 + (x1-1.5)^2/(2*v*v)), 0)
mean(vect)
```
(2)
```{r}
v = 1
x1 <- rnorm(n = 1000000, mean = 1.5, sd = v)
vect <- ifelse(x1<2 & x1>1,v * exp(-x1^2/2 + (x1-1.5)^2/(2*v*v)), 0)
mean(vect)
```
(3)
```{r}
v = 10
x1 <- rnorm(n = 1000000, mean = 1.5, sd = v)
vect <- ifelse(x1<2 & x1>1,v * exp(-x1^2/2 + (x1-1.5)^2/(2*v*v)), 0)
mean(vect)
```
Q4
(a)
`
`
`
`
`
`
`
`
`
`
```{r}
n = 1500
x <- runif(n)
vect <- 1/(1+x)
(I = mean(vect))
```
(b)
`
`
`
`
`
`
`
`
`
`
```{r}
n = 1500
b = (1- log(2)*3/2)/(1/12)
x <- runif(n)
vect <- 1/(1+x) - b * (1+x-3/2)
(Icv <- mean(vect))
```






